config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "recipes#index"
  resources :recipes, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form
  include ActiveModel::Model 
  attr_accessor :name, :image, :caption, :cooking_time, :user_id, :ingredient_name, :seasoning_name, :step

  with_options presence: true do 
    validates :name
    validates :caption
    validates :user_id 
  end

  def save 
    recipe = Recipe.create(name: name, image: image, caption: caption, cooking_time: cooking_time, user_id: user_id)
    Ingredient.create(ingredient_name: ingredient_name)
    Seasoning.create(seasoning_name: seasoning_name)
    Procedure.create(step: step)
  end
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe 
end

app/models/procedure.rb
class Procedure < ApplicationRecord
  belongs_to :recipe 
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :ingredients
  has_many :seasonings 
  has_many :procedures
end

app/models/seasoning.rb
class Seasoning < ApplicationRecord
  belongs_to :recipe 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes 
  
  validates :nickname, presence: true, length: { maximum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def new
    @form = Form.new
  end

  def create
    @form = Form.new(recipe_params)
    if @form.valid? 
      @form.save 
      redirect_to root_path
    else  
      render :new 
    end
  end

  private

  def recipe_params 
    params.require(:form).permit(:name, :caption, :cooking_time, :image, :ingredient_name, :seasoning_name, :step).merge(user_id: current_user.id)
  end

end

app/controllers/seasonings_controller.rb
class SeasoningsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/seasonings_helper.rb
module SeasoningsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rakumeshi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<ul class='lists-right'>
  <% if user_signed_in? %>
    <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li> 
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
  <% end %>
</ul>

<h1>トップページ</h1>

<% @recipes.each do |recipe| %>
  <div>投稿者：<%= recipe.user.nickname %></div>
  <div>料理の名前：<%= link_to recipe.name, "#" %></div>
  <div><%= link_to image_tag(recipe.image), "#" %></div>
  <div>料理の説明：<%= recipe.caption %></div>
  <div>調理時間：<%= recipe.cooking_time %>分</div><br>
<% end %>

<br><br><%= link_to '投稿する', new_recipe_path, class: "recipe-new" %>

app/views/recipes/new.html.erb
<h1>投稿ページ</h1>

<h2> 料理を投稿する</h2>
<%= form_with model: @form, url: recipes_path, local: true do |f| %>
  <%# レシピのフォーム %>
  <div>
    <%= f.label :name, "料理の名前" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :image, "料理の写真" %>
    <%= f.file_field :image, id:"item-image" %>
  </div>
  <div>
    <%= f.label :caption, "料理の説明" %>
    <%= f.text_field :caption %>
  </div>
  <div>
    <%= f.label :cooking_time, "調理時間(分)" %>
    <%= f.text_field :cooking_time %>
  </div>
  <%# ここまで %>

  <%# 材料のフォーム %>
  <div class="ingredients">
    <% %>
    <%= f.label :ingredient_name, "材料" %>
    <%= f.text_field :ingredient_name %>
  </div>
  <%# ここまで %>

  <%# 調味料のフォーム %>
  <div>
    <%= f.label :seasoning_name, "調味料" %>
    <%= f.text_field :seasoning_name %>
  </div>
  <%# ここまで %>

  <%# 作り方のフォーム %>
  <div>
    <%= f.label :step, "作り方" %>
    <%= f.text_area :step %>
  </div>
  <%# ここまで %>

  <%= f.submit "投稿する" %>
<% end %>

<br><br><%= link_to "投稿せずにトップページへ戻る", root_path %>